[package]
name = "birdai-tick"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
birdai-amm.workspace = true
birdai-move.workspace = true
move-core-types.workspace = true
sui-types.workspace = true
thiserror.workspace = true

[dev-dependencies]
bcs.workspace = true
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
